### ISSUE TITLE
Manifest File Could Not Be Found

### ISSUE THREAD

**Issue by jasonatclimbingtrees** [anvilinsights/data-studio#19]
As reported on Data Studio

**Comment by kyle-mccarthy** [comment]
Hi, could you provide me with a link to the report and information about what visualization or connector you are having an issue with? Thanks!

**Comment by jasonatclimbingtrees** [comment]
Hi Kyle, it was for the Data Target Card, but I'm happy to say it does now work again - I'm not quite sure what changed because I've certainly not changed anything on the report!
